sudo: false
language: go
go:
- 1.5.3
branches:
  only:
  - master
notifications:
  slack:
    secure: ZNs6KqNw8g0GdRtRuCNrZqaBvQhJNaxQjAoKGZTe1WKrMg1beJowxEi0UXwX1IHsETEcjHosyMmauHiwHdE+zYnFNHAPl6uViXs0hN6n6h5d5HMWuWUmlW8arRMXEhF+aehMiZLXYDLxyJVVEGlrekYSU9Q5bg5l/yQ0RbALRmsyoqpEVsp/IpENsMrGEr2216rwaDJdoGbkp+ufDj8E+lfDzEL2Zu8zE8ggXJRzHp8yYvWJF9BWNWdw/bZXf+KEirB6kT6NiEEg9E/sYNwyqd1aduq1VgBMWCVxk5DZ+nHyMLR8NqQfoGsTofohVpVt/bRc2h7ok8tx/W9g19avAqY8RvfZKdxfzm2Ne8LncXQZfW61xgMOa0e0s240/tfKfyB+OUqnBysIm0HKYRfi1IVm4EERF3TSm3eXv/6k+yFdezL8r5LKOgUl67wJwkXHWOS1aFu1dx9Ey7OZ/1LNOgTz4rvKzgEIVlt0dYYV8ZqRg4EzAo7GyT5jAFOtv3nTOMGzbLbDmMkeVQ7bFEVB3UwuPkU9WNeBKmw//HVjwc9egeqhnkoHcv1YswQfH6F00L8bBvrFeod1UDyovs2ogSCMF8nJwP9Xk8UzUFzv3k0fYVeEpCjhzkaqZwf8qdeSFyQGlpXiLhG4TGPwwbhUw7/hF8r/m69xNzLFppcFzwY=
